# Generated by Django 5.1.6 on 2025-03-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_alter_item_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("id",)},
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("list", "text")},
        ),
    ]
